services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Python.Dockerfile
    volumes:
      - .:/app/data_analyzer/
      - app_uv:/root/.cache/uv
    working_dir: /app/data_analyzer
    environment:
      PYTHONPATH: /app/data_analyzer/aws_lambdas
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true

volumes:
  app_uv:
    external: false
